### PR TITLE
Fix #37 (express middleware) 

### LINKED ISSUE #37: Throwing error doesn't work
I have noticed that throwing error in a resolver that handles file upload gives no result. Request hangs forever and api client never gets a response. Max file size limit doesn't throw any exceptions when limit is reached. 

Similar questions:
https://github.com/meabed/graphql-upload-ts/issues/78
https://github.com/flash-oss/graphql-upload-minimal/issues/19

### PR DESCRIPTION
**Pull request by Alex0007**
Copy solution to:
https://github.com/flash-oss/graphql-upload-minimal/issues/37

from:
https://github.com/meabed/graphql-upload-ts/pull/173/files

_Same kind of treatment is needed for Koa middleware though_

### CODE REVIEW

**Comment by Alex0007** [comment]
Why it stucks? Because middleware is checking only for `end` event, which is not happening in case of `error`

```
// Express
request.on("end", resolve)

// Koa
const finished = new Promise((resolve) => ctx.req.on("end", resolve));

```

**Comment by koresar** [comment]
Hello

Thank you for the contribution! 

The removed code ensures that the response is sent only after whole body of the request is consumed. Removing such protection seem dangerous to me.

You are likely right that it should handle error cases.
For that I recommend subscribing to more universal `close` event 
https://nodejs.org/api/http.html#event-close
Or maybe we should handle `error` event separately?

**Comment by Alex0007** [comment]
@koresar 

I just checked `close` event – not worked for me. 

I'm not sure this protection is needed.. It's Express Middleware, isn't it enough for `processRequest` to work correctly, to make middleware work without such protection?

**Comment by koresar** [comment]
I gave it another thought. You are likely right.

AFAIK the Node or Express won't allow you to send response until the whole request get's consumed. Adding such protection on top is likely useless. More-so harmful.

**Comment by koresar** [comment]
Published as  https://github.com/flash-oss/graphql-upload-minimal/releases/tag/v1.5.5

**Pull request merged**
